### ISSUE TITLE
Merge Genesis Agent Profiles

### ISSUE THREAD

**Issue by bhubbard** [agentevolution/wp-listings#13]
I think the Genesis Agent Profile plugin (https://wordpress.org/plugins/genesis-agent-profiles/) should be merged into the WP Listings plugin. Since its just a custom post type plugin there is no reason only genesis themes should be allowed to use it. It should be available to every user of WP Listings.

**Comment by davebonds** [comment]
Agreed. That will be developed into a standard WP plugin with no theme requirements, but because there are different use cases for each, they will be two different plugins.

**Comment by bhubbard** [comment]
Does this really need to stay as its own plugin? While it technically serves another function of adding the Custom Post Types for agents, its really gonna be used by the majority of the same users as WP-Listing as they are tied in together. Merging this plugin into WP-Listings will offer benefits such as one code base/plugin to manage, being able to merge css and js for site performance, etc.

**Comment by davebonds** [comment]
I totally understand, but still think it should be it's own plugin. There are many agents, and I'm not breaking news here, that don't want to put the time into creating their own listings (maybe because they rely on IDX), but will create profiles and photos for everyone in their office. So they have their own use cases and separate functionality. Tying two different solutions into a single plugin like that is just bloat for users that will only be using a part of the plugin.

**Comment by bhubbard** [comment]
Ok, can you go ahead and create the github repo? What are you gonna call it, "Agents for WP Listings"? I would like to fork it and help get development started so I can use it on a new client project.
